# Generated by Django 5.0.2 on 2024-03-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Gestor de Venta', 'Gestor de Venta'), ('Usuario del sistema', 'Usuario del sistema')], max_length=50, verbose_name='Rol de Usuario'),
        ),
    ]
