# Generated by Django 5.0.2 on 2024-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Gestor de Venta', 'Gestor de Venta'), ('Usuario del sistema', 'Usuario del sistema'), ('Administrador', 'Administrador')], max_length=50, verbose_name='Rol de Usuario'),
        ),
    ]
