# Generated by Django 5.0.2 on 2024-03-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del País')),
                ('estado_pais', models.CharField(max_length=150, verbose_name='Estado del País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Locacion_Turistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nombre_locacion', models.CharField(max_length=150, verbose_name='Locación Turística')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turistic_package.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Locacion_Turistica',
                'verbose_name_plural': 'Locaciones_Turisticas',
            },
        ),
        migrations.CreateModel(
            name='Paquete_Turistico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('actividades', models.CharField(max_length=50, verbose_name='Actividades')),
                ('estancia', models.CharField(max_length=150, verbose_name='Estancia')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('tiempo_estancia', models.PositiveIntegerField(verbose_name='Tiempo de Estancia')),
                ('calificacion', models.PositiveIntegerField(verbose_name='Calificación')),
                ('imagen_paquete', models.ImageField(blank=True, null=True, upload_to='paquetes_turisticos/', verbose_name='Imagen')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('locacion_turistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turistic_package.locacion_turistica', verbose_name='Locación Turística')),
            ],
            options={
                'verbose_name': 'Paquete_Turístico',
                'verbose_name_plural': 'Paquetes_Turísticos',
            },
        ),
    ]
