# Generated by Django 5.0.2 on 2024-03-21 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistic_package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete_turistico',
            options={'ordering': ['-id'], 'verbose_name': 'Paquete_Turístico', 'verbose_name_plural': 'Paquetes_Turísticos'},
        ),
        migrations.AlterField(
            model_name='paquete_turistico',
            name='actividades',
            field=models.CharField(max_length=250, verbose_name='Actividades'),
        ),
        migrations.AlterField(
            model_name='paquete_turistico',
            name='calificacion',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
    ]
