# Generated by Django 5.0.2 on 2024-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelo', '0002_alter_vuelo_aerolinea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'ordering': ['-id'], 'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='aerolinea',
            field=models.CharField(choices=[('Air Europa', 'Air Europa'), ('Interjet', 'Interjet'), ('Delta Airlines', 'Delta Airlines')], max_length=50, verbose_name='Aerolínea'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='imagen_vuelo',
            field=models.ImageField(blank=True, null=True, upload_to='vuelos/', verbose_name='Imagen'),
        ),
    ]
