# Generated by Django 5.0.2 on 2024-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelo', '0003_alter_vuelo_options_alter_vuelo_aerolinea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='aerolinea',
            field=models.CharField(choices=[('Interjet', 'Interjet'), ('Air Europa', 'Air Europa'), ('Delta Airlines', 'Delta Airlines')], max_length=50, verbose_name='Aerolínea'),
        ),
    ]
