# Generated by Django 5.0.2 on 2024-03-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turistic_package', '0002_alter_paquete_turistico_options_and_more'),
        ('vuelo', '0003_alter_vuelo_options_alter_vuelo_aerolinea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_Paquete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nombre_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turistic_package.paquete_turistico', verbose_name='Paquete Turístico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva_Paquete',
                'verbose_name_plural': 'Reservas_Paquetes',
            },
        ),
        migrations.CreateModel(
            name='Reserva_Vuelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creado', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.vuelo', verbose_name='Vuelo')),
            ],
            options={
                'verbose_name': 'Reserva_Vuelo',
                'verbose_name_plural': 'Reservas_Vuelos',
            },
        ),
    ]
