# Generated by Django 5.0.2 on 2024-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_paquete',
            name='aceptada',
            field=models.BooleanField(default=False, verbose_name='Aceptar Reserva'),
        ),
        migrations.AddField(
            model_name='reserva_paquete',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Petición de Reserva'),
        ),
        migrations.AddField(
            model_name='reserva_vuelo',
            name='aceptada',
            field=models.BooleanField(default=False, verbose_name='Aceptar Reserva'),
        ),
        migrations.AddField(
            model_name='reserva_vuelo',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Petición de Reserva'),
        ),
    ]
